version: '3.8'

services:
  mongonbd:
    container_name: mongonbd
    image: mongo:4.4
    volumes:
      - ~/mongors/data1:/data/vmdb
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
    ports:
      - 27021:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

networks:
  mongors-network:
    driver: bridge
# docker exec mongonbd /scripts/rs-init.sh